- platform: template
  sensors:
    bente:
      friendly_name: "bente"
      friendly_name_template: >-
       {% if is_state('device_tracker.huawei_p8:', 'home') %} 
           Hjemme
       {% elif is_state('device_tracker.huawei_p8_2', 'home') %}
           Hjemme
       {% else %}
          borte
       {% endif %}
      value_template: >-
       {% if is_state('device_tracker.huawei_p8_2', 'home') %}
           home
       {% elif is_state('device_tracker.huawei_p8', 'home') %}
           home
       {% else %}
           away
       {% endif %}
      entity_picture_template: "/local/tracker_images/bente.JPG"