- platform: template
  sensors:
    moto360:
      friendly_name: "moto360"
      value_template: >-
        {% if is_state('device_tracker.androiddc39f69c65e1ae1d_2', 'home') %}
            home
        {% elif is_state('device_tracker.androiddc39f69c65e1ae1d', 'home') %}
            home
        {% else %}
            away
        {% endif %}
      icon_template: mdi:watch
 