#kristoffer tab
#device_tracker.android852e83ffe121c955
#device_tracker.b
#device_tracker.b_2
- platform: template
  sensors:
    rune:
      friendly_name_template: >-
       {% if is_state('device_tracker.device_tracker.b', 'home') %} 
           Online
       {% elif is_state('device_tracker.device_tracker.b_2', 'home') %}
           Online
       {% else %}
           Offline
       {% endif %}
      value_template: >-
       {% if is_state('device_tracker.device_tracker.b', 'home') %} 
           Online
       {% elif is_state('device_tracker.device_tracker.b_2', 'home') %}
           Online
       {% else %}
           Offline
       {% endif %}
      entity_picture_template: "https://lh3.googleusercontent.com/-Og6ufQULDWc/AAAAAAAAAAI/AAAAAAAAHHI/yk-6zSnNyzo/s60-p-rw-no/photo.jpg"
  #unit_of_measurement: {{ "home" if is_state("device_tracker.runes7_runes7", "home") else "{{ 'home' if is_state('device_tracker.samsunggalaxys7', 'home') else 'away'}}" }}
