- alias: Volum nettradio
  trigger:
    platform: state
    entity_id: input_number.volum_nettradio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Livingroom") %} media_player.living_room_speaker
        {% elif is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_speaker
        {% endif %}
      volume_level: "{{ trigger.to_state.state | int }}"